# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        build: [macos, windows]
        include: 
          - build: macos
            os: macos-latest
            archive-name: darwin
          - build: windows
            os: windows-latest
            archive-name: windows
    
    permissions:
      contents: write

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.4
      - name: Download dependencies
        run: go mod download
      - name: Build
        run: go build -v -o copy2file .
        env:
          CGO_ENABLED: 1
      
      - name: Prepare Packaging
        if: matrix.build == 'macos'
        run: tar zcvf copy2file-${{ matrix.archive-name }}.tar.gz copy2file LICENSE
      - name: Prepare Packaging
        if: matrix.build == 'windows'
        run: tar zcvf copy2file-${{ matrix.archive-name }}.tar.gz copy2file.exe file2clip.exe LICENSE
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: copy2file-${{ matrix.archive-name }}.tar.gz
          path: copy2file-${{ matrix.archive-name }}.tar.gz
      - name: Release version
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: copy2file-${{ matrix.archive-name }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
